# Generated by Django 3.2.9 on 2021-11-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='eventImg')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventImg', to='events.events')),
            ],
        ),
    ]
