# Generated by Django 3.2.9 on 2021-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211117_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='img',
            field=models.ImageField(default='eventImg/l4.jpg', upload_to='eventImg'),
            preserve_default=False,
        ),
    ]
