# Generated by Django 3.2.9 on 2021-11-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_events_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='shortDes',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
