# Generated by Django 3.2.9 on 2021-11-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_events_shortdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
