# Generated by Django 3.2.9 on 2021-11-18 09:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20211118_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
