# Generated by Django 3.2.9 on 2021-11-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titie',
            new_name='title',
        ),
    ]
