# Generated by Django 3.2.9 on 2021-11-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='homeslider')),
                ('subtitle', models.CharField(max_length=20)),
                ('title', models.TextField(max_length=70)),
            ],
        ),
    ]
