# Generated by Django 3.2.9 on 2021-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211116_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='shortDiscription',
            field=models.TextField(max_length=120),
        ),
    ]
