# Generated by Django 3.2.9 on 2021-11-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homeslider_shortdiscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
