# Generated by Django 3.2.9 on 2021-11-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couses',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
