# Generated by Django 3.2.9 on 2021-11-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couses', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='couses',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
