# Generated by Django 3.2.9 on 2021-11-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couses', '0004_couses_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Couses', to='couses.category'),
        ),
    ]
