# Generated by Django 3.2 on 2021-11-30 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('couses', '0005_alter_couses_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('ammount', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('transactionid', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('couse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='couses.couses')),
            ],
        ),
    ]
