# Generated by Django 3.2 on 2021-12-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couses', '0009_auto_20211201_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmconfig',
            name='WEBSITE',
            field=models.CharField(choices=[('1', 'WEBSTAGING'), ('2', 'DEFAULT')], help_text='choose Webstaging for testiing and Default for production', max_length=100),
        ),
    ]
