# Generated by Django 3.2 on 2021-12-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couses', '0010_alter_paytmconfig_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaytmConfig',
        ),
    ]
