# Generated by Django 3.2.9 on 2021-12-06 05:34

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15, validators=[about.models.only_int])),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('otherPhone', models.CharField(help_text='Separate phone number with (,) Ex: 9876543210,9898921212,.......', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='openingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(help_text='Eg:Mon - Tues :', max_length=100)),
                ('time', models.CharField(help_text='Eg:6.00 am - 10.00 pm or closed', max_length=100)),
            ],
        ),
    ]
