# Generated by Django 3.2.9 on 2021-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contactinfo_openinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='footerlogo',
            field=models.ImageField(default='', upload_to='logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='otherPhone',
            field=models.CharField(help_text='Separate phone number with (,) Ex: +61 3 1234 5678 , +12 3 1234 5678.......', max_length=1000),
        ),
    ]
