# Generated by Django 4.1.1 on 2022-09-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20211206_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=80)),
                ('doj', models.DateField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('volunteer_image', models.ImageField(upload_to='volunteer_image')),
            ],
        ),
    ]
