# Generated by Django 4.1.1 on 2022-09-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_image',
            field=models.ImageField(upload_to='resume'),
        ),
    ]
