# Generated by Django 4.1.1 on 2022-09-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_volunteer_volunteer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='volunteer_image',
        ),
    ]
